quotes:
  1: "Hi Jedi, you got a brand new sandwich"
  2: "When you'll eat this sandwich, you'll understand the life meaning"
  3: "Vegan Burger is for *****"
  4: "General things sandwiches are awesome"
